### ISSUE TITLE
Image support for AGES 7.0?

### ISSUE THREAD

**Issue by MishaIac** [eplightning/afhook#1]
*changed at the request of aNCHOR*

**Comment by eplightning** [comment]
It's hard to tell what changed and I don't really remember how these functions used to work. I'll try to looking into it if I ever find the time but not sure when that will be.

If you're sure this is the same function I was hooking in the older engine version you can also try changing `__cdecl` to `__thiscall` since it seems that function does use `ecx` register to pass `this` pointer. This might help if they they changed these functions to be C++ method instead after moving entire code to a single .exe . 

You can also try `__fastcall` I suppose, text functions seem to use that calling convention instead.

More info (I know this is GCC doc but it basically means the same thing for VC++ compiler): https://gcc.gnu.org/onlinedocs/gcc/x86-Function-Attributes.html

**Comment by MishaIac** [comment]
I will try changing `__cdecl` to `__thiscall` or `__fastcall`.
As for whether the function is correct, I checked it with breakpoint. Of course, breakpoint triggered other functions as well, but these two look the most like the right ones. But I couldn't hook the text with afhook. I kind of found the right function, but it only has a pointer to the text in memory, not the text itself (maybe it's the wrong function after all, and I need to find a function that puts the text into memory?)

**Comment by MishaIac** [comment]
In fact, we're currently translating Melvina Maniax (which is part of Kimi ga Nozomu Muv-Luv) into English, and we're also translating the Muv-Luv Steam version into Russian. Both of these games on AGES 7.0. Of course, if you want, we'll mention you in the credits.

**Comment by MishaIac** [comment]
> I will try changing __cdecl to __thiscall or __fastcall.

Still crashing. Both with `__thiscall` and `__fastcall`. However, I noticed that if you remove everything from the function, and leave only `return`, then the game does not crash immediately at startup (you can leave `__cdecl`), as before, but crashes only when the main menu appears. It seems that the game crashes on startup due to SHA1 processing, but it's not clear why game crashes in the main menu.

**Comment by MishaIac** [comment]
Fortunately, I got the R6Ti sorted out.
Now I need to deal with the text.
And that's where I ran into trouble. I found the right function, and the right function argument, but the problem is that all the text is UTF-16 encoded, and because of that, afhook only takes out the first character of the text (although it takes out the whole Japanese text). This seems to be because there are `x00` in between characters. I tried searching for this on the internet, but I couldn't find anything specific to my situation. How can this problem be solved?
![image](https://user-images.githubusercontent.com/47920105/154767392-af080c0b-8420-41f0-b9ad-c9eaddedc884.png)

p.s. Maybe this problem can be solved easily, but alas, I don't know how, just because I'm not good at C++. I could say I'm still learning :D

**Comment by eplightning** [comment]
Older rUGP versions used SHIFT-JIS encoding where this wasn't an issue. If the new engine uses UTF-16 some modifications will be required:

- You need to modify string handling in AFHook.

If you're lucky and they simply switched from `char` to `wchar_t` type then you just need to update those types (char -> wchar_t) and update all function calls that used/operated on those strings (for example, `strncpy` to `wcsncpy`).

There's also a possiblity that they stopped using C-style strings (NULL terminated). However that's unlikely from what I can see so I wouldn't worry about it for now.

- AFEditor needs to be modified to encode strings in .pkg files using UTF-16 (should be easy, just find SHIFT-JIS and replace with UTF-16)

**Comment by MishaIac** [comment]
I've already tried using wchar_t, but it didn't work. It still only outputs the first character of the text. According to the debugger, the text is in `L"` which just requires wchar_t, but it doesn't work for some reason. According to the IDA, the required argument uses the type `unsigned int`, but as far as I know it can only store numbers, can't it?

**Comment by eplightning** [comment]
Weird, `wchar_t*` should work given the data you have in the screenshot. I wouldn't really rely on datatypes detected by IDA Pro, unsigned int is most likely just a pointer so it might be char* or wchar_t* or anything_else*.

**Comment by MishaIac** [comment]
I noticed that if you use static_cast<wchar_t *> you can get UTF-16 encoded text. However, if there is even a single Non Ascii character in the text, afhook stops get text, even text that has only ascii characters.

**Comment by tritiumjngn** [comment]
how did you manage to make ages 7.0 use the afhook plugin?

**Comment by MishaIac** [comment]
Solved.
